schema_version: 1

context:
  name: pynose
  version: "1.5.5"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pynose-${{ version }}.tar.gz
  sha256: 81da4e26473f98dd37497248eef4352d3221d1d56edf874a00c6bdda6daf7f49

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - nosetests = nose.core:run_exit
      - pynose = nose.core:run_exit

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=68.0.0
    - wheel >=0.42.0
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - nose
      python_version: ${{ python_min }}.*
      pip_check: true
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - nosetests --help
      - pynose --help

about:
  summary: pynose fixes nose to extend unittest and make testing easier
  license: LGPL-2.1-only
  license_file:
    - LICENSE
    - LICENSE.cpython
  homepage: https://github.com/mdmintz/pynose
  repository: https://github.com/mdmintz/pynose

extra:
  recipe-maintainers:
    - JaRoSchm
